name: train-my-modell
on: [push]
jobs:
  train:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: Runner
        run: |
          echo 'Hi!' >> report.md
          cml send-comment report.md
  
