name: train-my-model
on: [push]
jobs:
  train:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: cml_run
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $CODEBLOCK > report.md
          nvidia-smi >> report.md
          echo $CODEBLOCK >> report.md
          cml send-comment report.md
  
