name: train-my-model
on: [push]

jobs:
  train:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-tools@v1
      - name: cml_run
        env:
           name: SSL_CERT_DIR
           value: "/etc/ssl/certs"
       
        run: |
          echo $CODEBLOCK > report.md
          nvidia-smi >> report.md
          echo $CODEBLOCK >> report.md
          cml send-comment report.md
  
