name: train-my-model
on: [push]

jobs:
  train:
    runs-on: [self-hosted]
#    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: cml_run
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo 'Hi!'  > report.md
          cml send-comment report.md
  
